<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Description>Faura Integration Testing Library</Description>
		<RepositoryType>git</RepositoryType>
		<PackageTags>faura;testing;integrationTesting</PackageTags>
		<PackageReleaseNotes>NET 8.0+ compatibility version</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.17" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.17" />
		<PackageReference Include="Testcontainers" Version="4.6.0" />
		<PackageReference Include="NSubstitute" Version="5.3.0" />
		<PackageReference Include="xunit.core" Version="2.9.3" />
	</ItemGroup>

	<ItemGroup>
		<SonarQubeSetting Include="sonar.coverage.exclusions">
			<Value>**/**/*.cs</Value>
		</SonarQubeSetting>
	</ItemGroup>
</Project>