name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build and Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore src/Faura.sln

      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"JosepFe_faura" \
            /o:"josepfe" \
            /d:sonar.login="${SONAR_TOKEN}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="coverage/combined/coverage.opencover.xml"

      - name: Build solution
        run: dotnet build src/Faura.sln --no-restore --no-incremental

      - name: Run Unit Tests with Coverage (WebAPI)
        run: |
          dotnet test src/Templates/FFaura.WebAPI.IntegrationTests/Faura.WebAPI.IntegrationTests.csproj \
            --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=coverage/webapi/
      
      - name: Merge coverage reports
        run: |
          ~/.dotnet/tools/reportgenerator \
            -reports:"coverage/**/coverage.opencover.xml" \
            -targetdir:"coverage/combined" \
            -reporttypes:Html

      - name: End SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.login="${SONAR_TOKEN}"
